### ISSUE TITLE
機能が実行できないです

### ISSUE THREAD

**Issue by UpEveryDayAction** [vanvund97/Sosei-Project#4]
ラジオボタンから機能を立ち上げようとしたのですが、
エラーが起きてどうもtensorflowが必要なのかなといった感じです。

エラー＞
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\DearM\Documents\GitHub\Sosei-Project\Program\UI\UI.py", line 234, in funcStart
    Program01.main()
  File "C:\Users\DearM\Documents\GitHub\Sosei-Project\Program\function\Program01.py", line 27, in main
    landmarks = results.pose_landmarks.landmark
AttributeError: 'NoneType' object has no attribute 'landmark'

**Comment by UpEveryDayAction** [comment]
これは、相談事項の予定です。

**Comment by UpEveryDayAction** [comment]
カメラに画像のインプットがないので起きていたエラーでした。（解決）
